timeout: 3

/BoredOS
    protocol: limine

    kernel_path: boot():/boredos.elf
    #resolution: 1280x720
    module_path: boot():/bin/calculator.elf
    module_path: boot():/bin/crash.elf
    module_path: boot():/bin/hello.elf
    module_path: boot():/bin/notepad.elf
