timeout: 3

/BoredOS
    protocol: limine

    kernel_path: boot():/boredos.elf
    #resolution: 1280x720
    module_path: boot():/bin/calculator.elf
    module_path: boot():/bin/crash.elf
    module_path: boot():/bin/hello.elf
    module_path: boot():/bin/markdown.elf
    module_path: boot():/bin/minesweeper.elf
    module_path: boot():/bin/notepad.elf
    module_path: boot():/bin/paint.elf
    module_path: boot():/bin/settings.elf
    module_path: boot():/bin/txtedit.elf
    module_path: boot():/bin/viewer.elf
