timeout: 3
    
# Graphics mode and Splash screen
term_palette: ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff
term_background: #00000000
wallpaper: boot():/splash.jpg

/BoredOS
    protocol: limine

    kernel_path: boot():/boredos.elf
